"""empty message

Revision ID: 4dd3baaf3071
Revises: dab9eaebf94e
Create Date: 2022-04-16 16:32:54.539884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd3baaf3071'
down_revision = 'dab9eaebf94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['mobile_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_to_channel',
    sa.Column('playlist', sa.Integer(), nullable=False),
    sa.Column('radio_channel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['radio_channel'], ['radio_channel.id'], ),
    sa.PrimaryKeyConstraint('playlist', 'radio_channel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_to_channel')
    op.drop_table('playlist')
    op.drop_table('mobile_user')
    # ### end Alembic commands ###
